from __future__ import annotations

import json
from pathlib import Path

from brains.config import settings
from brains.control.common import normalize_path
from brains.control.sessions import register_workspace
from brains.storage.db import SessionLocal
from brains.storage.migrations import init_db
from brains.storage.models import (
    AgentSession,
    ApprovalRequest,
    Artifact,
    Event,
    Handoff,
    RouteDecision,
    Source,
    Trace,
    Workspace,
)


def _views_path(workspace_path: str | None = None) -> Path:
    configured = Path(settings.control.generated_views_dir)
    if configured.is_absolute():
        path = configured
    elif workspace_path:
        path = Path(normalize_path(workspace_path)) / configured
    else:
        path = Path.cwd() / configured
    return path


def _views_dir(workspace_path: str | None = None) -> Path:
    path = _views_path(workspace_path)
    path.mkdir(parents=True, exist_ok=True)
    return path


def _header(title: str) -> list[str]:
    return [
        f"# Brains - {title}",
        "",
        "_Generated from SQLite. Source of truth: Brains database. Do not edit this file manually._",
        "",
    ]


def refresh_views(workspace_path: str | None = None) -> dict:
    workspace = register_workspace(workspace_path or ".")
    try:
        from brains.control.memberships import operator_can_see_workspace
        from brains.control.operators import resolve_current_operator

        operator = resolve_current_operator()
        if not operator_can_see_workspace(operator.get("id"), workspace.id):
            return {"ok": True, "views_dir": str(_views_path(workspace.path))}
    except Exception:
        pass
    out_dir = _views_dir(workspace.path)
    init_db()
    with SessionLocal() as session:
        _write_state(session, out_dir, workspace.id)
        _write_ledger(session, out_dir, workspace.id)
        _write_decisions(session, out_dir, workspace.id)
        _write_handoffs(session, out_dir, workspace.id)
        _write_routes(session, out_dir)
        _write_docs_index(session, out_dir, workspace.id)
    return {"ok": True, "views_dir": str(out_dir)}


def _write_state(session, out_dir: Path, workspace_id: int) -> None:
    workspace = session.query(Workspace).filter(Workspace.id == workspace_id).one()
    active_sessions = (
        session.query(AgentSession)
        .filter(AgentSession.workspace_id == workspace_id, AgentSession.ended_at.is_(None))
        .all()
    )
    open_decisions = (
        session.query(ApprovalRequest)
        .filter(ApprovalRequest.workspace_id == workspace_id, ApprovalRequest.status == "open")
        .count()
    )
    active_handoffs = (
        session.query(Handoff)
        .filter(Handoff.workspace_id == workspace_id, Handoff.status == "active")
        .all()
    )
    lines = _header("STATE")
    lines += [
        f"- Workspace: `{workspace.slug}`",
        f"- Path: `{workspace.path}`",
        f"- Status: `{workspace.status}`",
        f"- Last touched: {workspace.last_touched_at or '-'}",
        f"- Last summary: {workspace.last_summary or '-'}",
        f"- Open decisions: {open_decisions}",
        f"- Active sessions: {len(active_sessions)}",
        f"- Active handoffs: {len(active_handoffs)}",
        "",
        "## Active Sessions",
        "",
    ]
    if not active_sessions:
        lines.append("_none_")
    else:
        lines += ["| Session | Tool | Started |", "|---|---|---|"]
        for row in active_sessions:
            lines.append(f"| `{row.id}` | {row.tool} | {row.started_at} |")
    out_dir.joinpath("STATE.md").write_text("\n".join(lines) + "\n", encoding="utf-8")


def _write_ledger(session, out_dir: Path, workspace_id: int) -> None:
    rows = (
        session.query(Event)
        .filter(Event.workspace_id == workspace_id)
        .order_by(Event.created_at.desc(), Event.id.desc())
        .limit(200)
        .all()
    )
    lines = _header("LEDGER")
    lines += ["| When | Kind | Session | Message |", "|---|---|---|---|"]
    for row in rows:
        message = (row.message or "").replace("|", "\\|").replace("\n", " ")[:180]
        lines.append(f"| {row.created_at} | {row.kind} | `{row.session_id or ''}` | {message} |")
    if not rows:
        lines.append("| - | - | - | _none_ |")
    out_dir.joinpath("LEDGER.md").write_text("\n".join(lines) + "\n", encoding="utf-8")


def _write_decisions(session, out_dir: Path, workspace_id: int) -> None:
    rows = (
        session.query(ApprovalRequest)
        .filter(ApprovalRequest.workspace_id == workspace_id, ApprovalRequest.status == "open")
        .order_by(ApprovalRequest.created_at.desc(), ApprovalRequest.id.desc())
        .all()
    )
    lines = _header("DECISIONS-OPEN")
    if not rows:
        lines.append("_No open approval requests._")
    for row in rows:
        lines += [
            f"## {row.code} - {row.title}",
            "",
            f"- Filed: {row.created_at}",
            f"- Proposed: {row.proposed_answer or '-'}",
            "",
            row.body or "",
            "",
        ]
    out_dir.joinpath("DECISIONS-OPEN.md").write_text("\n".join(lines) + "\n", encoding="utf-8")


def _write_handoffs(session, out_dir: Path, workspace_id: int) -> None:
    rows = (
        session.query(Handoff)
        .filter(Handoff.workspace_id == workspace_id)
        .order_by(Handoff.set_at.desc(), Handoff.id.desc())
        .limit(50)
        .all()
    )
    lines = _header("HANDOFFS")
    if not rows:
        lines.append("_No handoffs._")
    for row in rows:
        lines += [
            f"## #{row.id} - {row.title}",
            "",
            f"- Status: {row.status}",
            f"- Set: {row.set_at}",
            "",
            row.body or "",
            "",
        ]
    out_dir.joinpath("HANDOFFS.md").write_text("\n".join(lines) + "\n", encoding="utf-8")


def _write_routes(session, out_dir: Path) -> None:
    routes = session.query(RouteDecision).order_by(RouteDecision.id.desc()).limit(100).all()
    traces = session.query(Trace).order_by(Trace.id.desc()).limit(20).all()
    lines = _header("ROUTES")
    lines += [
        "## Recent Route Decisions",
        "",
        "| ID | Task | Tier | Created |",
        "|---:|---|---|---|",
    ]
    for row in routes:
        lines.append(f"| {row.id} | {row.task_type} | {row.model_tier} | {row.created_at} |")
    if not routes:
        lines.append("| - | - | - | - |")
    lines += ["", "## Recent Traces", "", "| ID | Route | Created |", "|---:|---|---|"]
    for row in traces:
        lines.append(f"| {row.id} | {row.route} | {row.created_at} |")
    out_dir.joinpath("ROUTES.md").write_text("\n".join(lines) + "\n", encoding="utf-8")


def _write_docs_index(session, out_dir: Path, workspace_id: int) -> None:
    source = (
        session.query(Source)
        .filter(Source.workspace_id == workspace_id, Source.source_type == "docs_dir")
        .order_by(Source.updated_at.desc(), Source.id.desc())
        .first()
    )
    lines = _header("DOCS-INDEX")
    if source is None:
        lines.append("_No docs index has been generated yet._")
    else:
        rows = (
            session.query(Artifact)
            .filter(Artifact.source_id == source.id)
            .order_by(Artifact.mtime.desc(), Artifact.path.asc())
            .all()
        )
        lines += ["| Path | Modified | Size | Title | Summary |", "|---|---|---:|---|---|"]
        for row in rows:
            metadata = json.loads(row.metadata_json or "{}")
            stale = " stale" if metadata.get("stale") else ""
            summary = (row.summary or "").replace("|", "\\|")
            title = (row.title or "").replace("|", "\\|")
            modified = row.mtime.date().isoformat() if row.mtime else "-"
            lines.append(f"| `{row.path}` | {modified}{stale} | {row.size} | {title} | {summary} |")
    out_dir.joinpath("DOCS-INDEX.md").write_text("\n".join(lines) + "\n", encoding="utf-8")
